### ISSUE TITLE
Call to undefined function Hello\Fulcrum\Addon\init_theme()

### ISSUE THREAD

**Issue by MattRy** [hellofromtonya/Fulcrum#5]
I created the mu_autoloader.php file per previous issue response. I'm getting stopped with an undefined function error when activating the hellofromtonya theme.

What does the init_theme function look like/where can I find it? How do I pull it in?

ref line 17 in hello\functions.php:
$hello = Fulcrum\Addon\init_theme( __DIR__ . '/config/theme.php' );

**Comment by hellofromtonya** [comment]
Matt,

The `functions.php` has its own namespace, which is called `Hello`.  Fulcrum has its own namespace.  You need to use the fully qualified name for the function `init_theme()` in order to pull it into the `Hello` namespace.

`$hello = \Fulcrum\Addon\init_theme( __DIR__ . '/config/theme.php' );`

Notice that it starts with a backslash before `Fulcrum\Addon\init_theme`.

**Comment by hellofromtonya** [comment]
To learn more about Namespacing, see the [Ins and Outs of PHP Namespacing for WordPress](https://knowthecode.io/labs/ins-outs-php-namespace-wordpress) lab on [Know the Code](https://https://KnowTheCode.io).

**Comment by MattRy** [comment]
I have corrected the typo in the functions.php so that the proper namespace reference is used. The trouble is finding the function \Fulcrum\Addon\init_theme(). It doesn't appear to be defined anywhere in the Fulcrum mu plugin or the Hello theme.

**Comment by hellofromtonya** [comment]
Hey Matt,

The `Hello` theme uses an isolated and old version of Fulcrum that I did not publish.  I ended up abandoning that version, which is why you can't find it.  This weekend, I'll update the Hello theme to remove Fulcrum from it.
